# Generated by Django 4.2.27 on 2025-12-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_slug_restaurant_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
