# Generated by Django 4.2.27 on 2025-12-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_product_slug_alter_restaurant_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderItem',
        ),
    ]
