# Generated by Django 4.2.27 on 2025-12-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='orders.restaurant'),
            preserve_default=False,
        ),
    ]
