# Generated by Django 4.2.27 on 2025-12-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_user_address_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_delete',
        ),
    ]
