# Generated by Django 4.2.27 on 2025-12-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_restaurantaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
    ]
